 name: vkyc
 channels:
     - conda-forge
     - anaconda
     - defaults
     - ericmjl
 dependencies:
     - python=3.6
     - av
     - dlib
     - opencv
     - pip
     - pip:
          - nepali-roman
          - facenet-pytorch
          - streamlit-webrtc
          - numpy
          - scipy
          - face-recognition
          - easydict
          - matplotlib
          - mtcnn
          - nltk
          - numpy
          - pandas
          - Pillow
          - pytesseract
          - scipy
          - streamlit
          - torchvision
          - tensorflow
          - torch
          - keras-facenet
          - mediapipe
